/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <ZCMD.sp>

public Plugin:myinfo = 
{
	name = "ZBot",
	author = "Zakrzu",
	description = "<- Description ->",
	// DEV MAJOR MINOR FIX BUILD
	version = "D0.1.0.1",
	url = "<- URL ->"
}

public OnPluginStart()
{
	// Add your own code here...
}
