/* Plugin Template generated by Pawn Studio */

#define GS_NO_GAME 0
#define GS_WARMUP 1
#define GS_KNIFE 2
#define GS_KNIFE_AFTER 3
#define GS_MATCH 4

static int g_GameState = GS_NO_GAME;

public Create(char TeamName1[] char TeamName2[] bool demorec)
{
	//SETTEAMNAME
	
	//SETDEMOREC
	
	g_GameState = GS_WARMUP;
	return;
}

public Delete(bool restart)
{
	if(restart)
	{
		//RESTART SERVER
		return;
	} else {
		//RESTART MAP
		return;
	}
}

public PauseMatch()
{
	//PAUSE
	return;
}

public UnPauseMatch()
{
	//UNPAUSE
	return;
}

public ForceReady(int team)
{
	if(team == 0)
	{
		//BOTH READY
		return;
	} else if(team == 1)
	{
		//TEAM 1
		return;
	} else if(team == 2)
	{
		//TEAM 2
		return;
	}
	return;
}

public DemoRecord(bool demorec)
{
	if(demorec)
	{
		//rec
		return;
	} else {
		//norec
		return;
	}
}

public ChangeMap(char mapname[])
{
	//ChangeMAP
	return;
}

public SetKnifeRound(bool knifeRound)
{
	if(knifeRound)
	{
		//Set
		return;
	} else {
		//Set no
		return;
	}
}

public SetAllRounds(bool allRounds)
{
	if(allRounds)
	{
		//AllRounds
		return;
	} else {
		//Standard
		return;
	}
}

public SkipKnife(int winner)
{
	g_GameState = GS_KNIFE_AFTER;
	
	return;
}